sudo: required
services:
  - docker

before_install:
  - docker build -t marley/docker-react -f Dockerfile.dev .

script:
  - docker run marley/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-app"
  env: "Dcoker-env"
  bucket_name: "elasticbeanstalk-us-west-2-3064766"
  bucket_path: "docker-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
